collections:
  2022 Winners:
    tmdb_list_details: 8196548
    url_poster: https://github.com/dtjohnson90/PlexServer/blob/main/assets/2022.png?raw=true
  2021 Winners:
    tmdb_list_details: 8196631
    url_poster: https://github.com/dtjohnson90/PlexServer/blob/main/assets/2021.png?raw=true
  Marvel Cinematic Universe:
    tmdb_list_details: 1
    url_poster: https://github.com/dtjohnson90/PlexServer/blob/main/assets/avengers.jpg?raw=true
